name: flowy_infra
description: AppFlowy Infra.
version: 0.0.1
homepage: https://appflowy.io

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  path: ^1.8.3
  time: ">=2.0.0"
  uuid: ">=2.2.2"
  bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  file_picker: ^8.0.2
  file: ^7.0.0

dev_dependencies:
  build_runner: ^2.10.2
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.5.4
